json.first_name student.first_name
json.last_name student.last_name
json.email student.email
json.password student.password
json.phone_number student.phone_number
json.bio student.bio
json.linked_in_url student.linked_in_url
json.twitter_handle student.twitter_handle
json.personal_url student.personal_url
json.resume_url student.resume_url
json.github_url student.github_url
json.photo student.photo
